# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AutoClaim

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "1 */6 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Nodejs
      run: |
        sudo apt-get install nodejs -y
        npm install
    - name: Claim rewards | youalreadydead
      run: |
        npm start ${{ secrets.username }} ${{ secrets.password }} 0

